### ISSUE TITLE
aead.dev/mem (and aead.dev/minisign) do not support GOPROXY=direct

### ISSUE THREAD

**Issue by jimrobinson** [aead/mem#11]
I initially had some difficulties building minio on my Fedora based host because the Fedora package builders override the default `GOPROXY` value, changing it from the default `GOPROXY=https://proxy.golang.org,direct` to `GOPROXY=direct`, and this caused `go mod` to be unable to download the aead.dev modules.

The changes they make, see https://developer.fedoraproject.org/tech/languages/go/go-installation.html, make me think they are probably making deliberate changes based on official privacy policies [Edit: confirmed the changes are deliberate due to privacy concerns: https://fedoraproject.org/wiki/Changes/golang1.13#Detailed_Description].

Reverting to the documented golang defaults resolved the build issue for me, but I wanted to note that the Fedora default of `GOPROXY=direct` means that one cannot download the aead.dev/mem and aead.dev/minisign modules.  Here is an example with aead.dev/mem if I override GOPROXY like the Fedora golang package does:

```
$ docker run --rm -e GOPROXY=direct amd64/golang:1.22 go mod download -x aead.dev/mem@v0.2.0
# get https://aead.dev/mem?go-get=1
# get https://aead.dev/mem?go-get=1: 200 OK (0.173s)
go: aead.dev/mem@v0.2.0: unrecognized import path "aead.dev/mem": parse https://aead.dev/mem?go-get=1: no go-import meta tags ()
```

**Comment by aead** [comment]
This happens because the aead.dev/mem html is malformed.
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title></title>
    <link rel="stylesheet" href="http://127.0.0.1:1111/global.css">
    <meta name="description" content="">
    <meta property="og:title" content="">
    <meta property="og:description" content="">
    <meta property="og:type" content="website">

    <meta property="og:url" content="http://127.0.0.1:1111/mem/">
    <link rel="canonical" href="http://127.0.0.1:1111/mem/">

  </head>
  <body>
    <header></header>
    <main>

  <head>
    <meta name="go-import" content="aead.dev/mem git https://github.com/aead/mem">
    <meta http-equiv="refresh" content="0;URL='https://github.com/aead/mem'">
</head>
<body>
    Redirecting you to the <a href="https://github.com/aead/mem">project page</a>
</body>


    </main>j
```

I'll fix this.

**Comment by aead** [comment]
Should be fixed now. I can download via `GOPROXY=direct go get aead.dev/mem@latest`. Please re-open if you still have this issue.
